catch(std::exception& e)
{
  cerr<<"Fatal: "<<e.what()<<endl;
}